### ISSUE TITLE
Backup does not start - no feedback

### ISSUE THREAD

**Issue by nicolinux** [Anthony25/virt-backup#14]
Might be related to #13 
I have updated to virt-backup 0.1.5 and when I start the backup, the command returns immediately -  there is not feedback if something went wrong. Nor do I see any backups in progress.
Triggering backups with these commands:
`virt-backup backup`
`virt-backup -d backup`

Btw. one more thing - the help for  `-d` switch is misleading. It says "set the debug level" which implies that it expects a parameter - the debug level. But that's not explained anywhere. These commands trigger an error:
`virt-backup -d debug backup`
`virt-backup -d 9 backup`

**Comment by Anthony25** [comment]
Hi @nicolinux,
Thanks again for the bug report! I do not think it is related to #13, my backups continue to work without an issue. However, maybe no libvirt domain matches with your group rules?

I will try to improve the `list` sub-command in the next hours: currently, it only list domains having at least one complete backup, but there should be an option (`--all` for example) to list all domains matching for each group. It should help you (and others) to debug when nothing seems to match.

About the debug option, thanks about the feedback. By this description, I meant "toggle the debug level" (because behind the hood, it set the global logger at the `DEBUG` level). I will change it ASAP to be clearer.

**Comment by nicolinux** [comment]
Thanks for the quick reply (again).
These are my domains (it is only a test installation):
`# virsh list --all`
output:
```
Id    Name                           State
----------------------------------------------------
 -     win10                          shut off
 -     win7                           shut off
```

Given this config, it should find the domain, right?
```
debug: True
uri: "qemu:///system"
username:
passphrase:
default:
  daily: 4
  weekly: 2
  monthly: 5
  yearly: 1
groups:
  test:
    target: /mnt/usb/kvm/_backup
    compression: None
    autostart: False
    hourly: 1
    daily: 3
    weekly: 2
    monthly: 5
    yearly: 1
    hosts:
      - host: win7
```
I am not sure about this bit from the example config:
`- host: domainname`
It looks to me like "host" is the key and "domainname" is the value. Or does it expect the hostname of the kvm host? Then in my case it would be something like:
`- mylinuxserver: win7`


I think when the `-d` switch is used, something should be always returned. In this case (if possible) something like "no domains found for backup. Check your config".

**Comment by Anthony25** [comment]
I am really sorry for the delay, it took way too long for me to add this option…

@nicolinux: Can you try with the last commit in master if your host is listed by `virt-backup ls -a` please?

**Comment by Anthony25** [comment]
Hi,
Any news about this issue?

**Comment by Anthony25** [comment]
I'm closing this issue since I didn't have any answer for the last several months.
